export const RESET_STATE = "RESET_STATE";

// hints
export const SET_SNACKBAR = "SET_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const SET_HELPER_TEXT = "SET_HELPER_TEXT";

export const SET_SOCKET = "SET_SOCKET";
export const SET_USERNAME = "SET_USERNAME";
export const DATA_UPDATE_RECEIVED = "DATA_UPDATE_RECEIVED";
